version: 2

jobs:
  8_0-bionic:
    docker:
      - image: swift:5.0-bionic
      - image: circleci/mysql:8.0
        name: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - checkout
      - run: apt-get -y install openssl libssl-dev
      - run: swift build -Xswiftc -DTEST_TLS
      - run: swift test -Xswiftc -DTEST_TLS
  5_7-bionic:
    docker:
      - image: swift:5.0-bionic
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - checkout
      - run: apt-get -y install openssl libssl-dev
      - run: swift build
      - run: swift test
  8_0-xenial:
    docker:
      - image: swift:5.0-xenial
      - image: circleci/mysql:8.0
        name: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - checkout
      - run: apt-get -y install openssl libssl-dev
      - run: swift build -Xswiftc -DTEST_TLS
      - run: swift test -Xswiftc -DTEST_TLS
  5_7-xenial:
    docker:
      - image: swift:5.0-xenial
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - checkout
      - run: apt-get -y install openssl libssl-dev
      - run: swift build
      - run: swift test
workflows:
  version: 2
  tests:
    jobs:
      - 8_0-bionic
      - 5_7-bionic
      - 8_0-xenial
      - 5_7-xenial
