version: '3'

x-shared-config: &shared_config
  platform: linux/amd64
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    MYSQL_DATABASE: test_database
    MYSQL_USER: test_username
    MYSQL_PASSWORD: test_password
  ports:
    - 3306:3306

services:
  percona-8_0:
    image: percona:8.0
    <<: *shared_config
  percona-5_7:
    image: percona:5.7
    <<: *shared_config
  mariadb-10_7:
    image: mariadb:10.7
    <<: *shared_config
  mariadb-10_2:
    image: mariadb:10.2
    <<: *shared_config
  mysql-8_0:
    image: mysql:8.0
    <<: *shared_config
  mysql-5_7:
    image: mysql:5.7
    <<: *shared_config
