/// The metadata reported by the server for the most recent command.
///
/// This metadata is contained in every `OK_Packet`, regardless of whether or not that packet followed
/// a `COM_QUERY` or `COM_STMT_EXECUTE` command; it is effectively stale as soon as the current active
/// command handler is done.
struct MySQLQueryMetadata {
    /// The number of "affected" rows for the query.
    let lastAffectedRows: Int
    
    /// The last inserted ID value.
    ///
    /// Not guaranteed to be meaningful except after a query command which ran an INSERT query. Not
    /// guaranteed to be meaningful if multiple statements were executed by a single query command.
    /// Not guaranteed to be meaningful across transactions.
    let lastInsertId: UInt64
    
    /// The number of warnings, if any, generated by the last command.
    ///
    /// Warnings persist only until the next command is issued.
    let lastWarningCount: Int
}
